#!/bin/sh

export DIR=`dirname $0`
export PRO=`basename $0`

export JAVA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=8989,server=y,suspend=n ${JAVA_OPTS}"
#export JAVA_OPTS="-Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=38172 -Dcom.sun.management.jmxremote.rmi.port=38172 -Djava.rmi.server.hostname=8.140.141.11"
export JAVA_OPTS="${JAVA_OPTS} -Xms1G -Xmx1G"

$DIR/springboot.sh  $PRO org.datayoo.brackets.BracketsApp  $1 $2 

