#!/bin/bash

export DIR=`dirname $0`
export PRO=`basename $0`

export JAVA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=39501,server=y,suspend=n ${JAVA_OPTS}"

$DIR/springboot.sh  $PRO org.datayoo.dencho.DenchoWebApplication  $1 $2 

