#!/bin/bash

export DIR=`dirname $0`
export PRO=`basename $0`

export JAVA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=38502,server=y,suspend=n ${JAVA_OPTS}"

export JAVA_OPTS="-Xms800M -Xmx800M ${JAVA_OPTS}"


$DIR/springboot.sh  $PRO org.datayoo.sengee.SengeeWebApplication  $1 $2 

