yc.cli.servers=datayoo.sengee:8822
yc.calling.expiration=20000
yc.cli.failure.retries=0

morten.node.id=denchoNode1
morten.node.leaf.configfile=./config/dencho-flow.xml
morten.node.propsware.path=./propsware
morten.node.leaf.storagepath=./data
morten.node.leaf.configmode=LocalPriority
morten.node.tags=nodeTypes:dencho
morten.node.comm.type=Netty
morten.node.leaf.workmode=Online

morten.node.leaf.shellserverport=39502

#oyez.node.port=32023
#oyez.node.log.conf=./conf/log.property
#oyez.node.nativeLibs=opencv_java460

#java.library.path=./ld
