application:
  version: 1.0-SNAPSHOT
authorization:
  clients: authx,brackets,sengee
  realm: datayoo
spring:
  datasource:
    url: jdbc:mysql://datayoo.mysql:3306/authx?characterEncoding=UTF8&useSSL=false
    username: root
    password: datayoo@123
    driverClassName: com.mysql.cj.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-idle: 100
    max-wait: 10000
    max-lifetime: 800000
    validation-queury: SELECT 1
    test-while-idle: true
    time-between-eviction-runs-millis: 27800
    test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  servlet:
    multipart:
      max-file-size: 700MB
      max-request-size: 700MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  servlet:
    context-path: /authx
  port: 38700
  maxSavePostSize: 2097152

feign:
  hystrix:
    enabled: false

logging:
  config: classpath:logback-pro.xml

console:
  log:
    level: INFO

swagger:
  enable: true

redirect:
  path: /admin

brackets:
  remote:
    url: http://datayoo.brackets:38600/brackets

sengee:
  service:
    url: http://datayoo.sengee:38500/sengee

tozoo:
  service:
    url: http://172.31.179.129:38800/member

authx:
  service:
    url: http://172.31.179.129:38700/authx
auth:
  adapter:
  navigators:
    - name: BO2XB7wbzH0H+xDo2WwH9A==
      uri: sD89yDfzBHjFdXwZhlfaCw==
    - name: juPopZ4cXwVj1F1J7HAF3w==
      uri: DgWhiWcMK86hQQbplM8JpQ==
    - name: 2CLgURAQbursdHBUfCWUzW7cVEQq8kLtv0R9G8aFrEI=
      uri: Jzefe55UFmlauPO1IO0DS3tF5IH7JoZgR8GGTlIdTvY=
    - name: 2CLgURAQbursdHBUfCWUzapw2vj3D+6P9w5gWgAr1No=
    - name: 2CLgURAQbursdHBUfCWUzUzgSEoRrO373wWQ1kS/cUU=
    - name: r5UwB/688Cm6R87V5EOliC47m3iuNW3Z+AvI1PZWoZE=
      uri: DhybVMcv53r3lfc226s/wREXLs3bTyl/f1xEhrB+F+U=
    - name: r5UwB/688Cm6R87V5EOliOdNLZw61DqJbOvXT/tttK4=
    - name: r5UwB/688Cm6R87V5EOliMnT+5rDZFqdqBjlBIYd3Wc=
    - name: BkpFAN1x60mF4Fb2CvpmXjXKkkAeL59C5GmrFfy39LQ=
    - name: BkpFAN1x60mF4Fb2CvpmXuzFfxtzeE1PEjqrIHpaVAo=
    - name: 6soqZou1LP0btFw0VkNA9erlA/tFxHsAgS4YMrqkjrY=
      uri: RvOkWYyofWvoNIDbzxO7bS47m3iuNW3Z+AvI1PZWoZE=
    - name: 6soqZou1LP0btFw0VkNA9SLsfHKQGSQsTAS6HRP+QjQ=
    - name: 6soqZou1LP0btFw0VkNA9ZX2s3OinLLMZ+O/+XTQUDs=
    - name: FBZsZie+EM/D9IZ+LOCkMw==
      uri: hoGdMDlDdCtJ2ZDDfmJuJA==
    - name: Y50i/raHquK2oNvgubjLvQ==
      uri: nZ8FPSViDxip2ymoOaLvsQ==
    - name: khKdsvxkhykeC5Tssp3/XqGOyzU/AVnPbHmGsV977SY=
      uri: VzxI16RatePtw3hgwL4Wvaq+7svqWFt1yOMQEnVgttE=
    - name: STJpGWU+ORjsFp7YSWKxbw==
      uri: 6QIuVHaqwQ63YEdGut4b/w==
    - name: AauQehSTP9byOqUtoTuhIQ==
      uri: Im8DQ08z5xgrwrTFpcB6Rg==
    - name: Jmlz5thSxXt5D9BgH08SS0Zz2dXYgEKRRPM/XrHhQks=
    - name: 5ATkF4iyAmzmU6T8w+8UvKRWoUb4u7t9DjYGtO85ilI=
    - name: lj3BYuztyBhxKiQcg+l4VA==
      uri: 8As5ndg38iMpkBEuVb1CTw==
    - name: 5EwQQKvEk/33zirJ2fHjbg==
      uri: 1SFqemkeVChON/aNC1e26A==
    - name: vjhz4U5h6cOddJNQxnmCQQ==
      uri: BGgvHgXLVJe3m/JOQhka6A==
    - name: TLL2AlSacO7NhNjRYcGWvDpeeg7WUGCuG2tJZG/jAzw=
    - name: TLL2AlSacO7NhNjRYcGWvOPG0vl1WluERBCEoWQ1mhA=
    - name: mjWleMRLJ5wwO4Zm/8+QFwQW09g2/Yb7BvEv/fPB8C4=
      uri: tMKjCUVTZe4tsD5Z7gMROt/N1+9xez/9x6mfc5jjHNE=
    - name: ZwL/32nI0PU3bFt6vl0aeQ==
      uri: cQmt++iUBq04gjRp1GMMgQ==
    - name: poJwk9MYPScwn/pMW1CcuF3hPx13UT+YPUbm5iAmE74=
      uri: AH7M1DiYBYwBKX2vZ4/BxR9qqBUeFRT/frSbMi2Nyag=
    - name: poJwk9MYPScwn/pMW1CcuJP2irmzs3czt7fvSptRxwY=
    - name: poJwk9MYPScwn/pMW1CcuNsl1KQgfkVXmhvZoKvCXtc=
    - name: +9et1/J5NcwaHO4Shj2xDyJ5CAVfI2K5XE/sVI4ysZo=
      uri: niPDVf/KJLWqbgYW+ChtBF3hPx13UT+YPUbm5iAmE74=
    - name: +9et1/J5NcwaHO4Shj2xD1NzCm6ZkD0AViko+32rgNs=
      uri: niPDVf/KJLWqbgYW+ChtBKT0mWVoBn3Nf0wj4z0FGnc=
    - name: IgNNvcTy9KGZ3o8j/RLRrzHS0eQAjgjlrJn0CtoNgHc=
      uri: 4h72JTjJEWIgE2eCxKyTFD8h06LVQTFYJ3DvqYTtf0c=
    - name: IgNNvcTy9KGZ3o8j/RLRr5PTh0tGwTzvm57tKCNEblw=
      uri: 4h72JTjJEWIgE2eCxKyTFFijpo27QpPlitA7n707o3o=
    - name: LeKtbZDH32JNO73kNsLDNsEC6DlJAhMfSrzcOpL3O4Y=
      uri: bkQ8A4DwJZXnnBQkIaqhzhwY+kgO06uHLDrz/UoTyOc=
    - name: I2SKByozrxJzvNqzUlTV3A==
      uri: 3RB1OalGAMsuXDsZxmxQQ5OEfdfnYlHAjjs3GgF343s=
    - name: lqENAryztVkc2dL3r7V/zD0OpiP4rgEbjrKCZMsVYsE=
      uri: hb/r68Uv8rw+CgCVxtxd48kn8wmj9UkyhcCY4ce+InE=
    - name: k9OHS0bBPO+bnu0oI0RuXA==
      uri: WKOmjbtCk+WK0DufvTujeg==
    - name: 8/RFezmFGQzN1LyjhIUUjA==
      uri: lIL+70efWzYPiOPb5ATqEpOEfdfnYlHAjjs3GgF343s=
    - name: 88R8/fXVQ5X2KrlKQ+uOI5OEfdfnYlHAjjs3GgF343s=
      uri: 1a+lVCgJ7yjv+fgw3h1GcZo/B1U4zIs1jQm6GNLi4Es=
    - name: 88R8/fXVQ5X2KrlKQ+uOI1wN/+lfvGZzruwyaYRoJ6I=
      uri: 1a+lVCgJ7yjv+fgw3h1Gcb1htJaNHjslaP1mFGyAyOc=
    - name: 88R8/fXVQ5X2KrlKQ+uOI2GLgt+pc6vsfbCl9T1JkG8=
      uri: 1a+lVCgJ7yjv+fgw3h1GcdtWBe9n9wM3SlE0DE1xR/s=
    - name: 88R8/fXVQ5X2KrlKQ+uOIzzDzFM4sdUfkuhBVFcKr5Q=
      uri: 1a+lVCgJ7yjv+fgw3h1GcdYal4Hfh2qPK/sc2/s6aLo=
    - name: 88R8/fXVQ5X2KrlKQ+uOI5WeTyf3+p5EHDrV/R4NXrgowN35As82pxrnykEVSyyf
    - name: 88R8/fXVQ5X2KrlKQ+uOI7IdjVAPsPS2mkLvc2E8fJI=
      uri: 1a+lVCgJ7yjv+fgw3h1GcWRc6CzBi0G+ZP79IocyR+Y=
    - name: QMm+VMgeQhNZ2zX/HsBdng==
    - name: Mpj636FEnbjQtYM82G/wRw==
      uri: nKDJ4peAFGOJtiHaI+rs/Q==
    - name: c4LkptV3Q4U//wjLd2tX9w==
    - name: KowtQDxB9wo9sPWuuNpkgg==
    - name: Qzdq4VG3evmdVquQLGUJxQ==
      uri: qHhU3hsOZ45tGlz4oPYH9A==
    - name: fHyP6omUKg9uG+KSVGRRPkZz2dXYgEKRRPM/XrHhQks=
    - name: v97eaBro2ORx5P0++jh2Ww==
      uri: gIPptNaxYdYxnpRy/ZOApQ==
    - name: 1DTHMxlqOmcJym9ENqyKKQ==
    - name: Xudv8a2oCRTMDauQhUpyHg==
      uri: zBz0tZ5NYcPftKiJKaZZkpOEfdfnYlHAjjs3GgF343s=
    - name: Ocr4ihOuIWjoZBBuxWGzvNTDNeDqArJ9Jy6bO4s7KCY=
    - name: idculi8V1yIq1sju//GDmA==
      uri: 4h72JTjJEWIgE2eCxKyTFJOEfdfnYlHAjjs3GgF343s=
    - name: pSGvXFAEx50A2waJmtooILNJHDt9NM8Psxg28DxfT5w=
      uri: bcq4for3bXrL7a9XwumY/U1CeiX0upHxkP+HupsSYHM=
    - name: idculi8V1yIq1sju//GDmA==
      uri: 4h72JTjJEWIgE2eCxKyTFJOEfdfnYlHAjjs3GgF343s
    - name: KIatH1vxyJ1ZYmYOHneSS6aoALgUQ7SKvFhVKy0cM2M=
    - name: KIatH1vxyJ1ZYmYOHneSS8vMksVxy60RTV2YAiZJ6Rk=
    - name: KIatH1vxyJ1ZYmYOHneSS5yNWsLVHCKcqhtwNadBA1I=
  entityTypes:
    - name: AuthSetting
      client: authx
      behaviors: update,delete
    - name: ResourceSpace
      client: authx
      behaviors: enter,update,delete
    - name: Authorization
      client: authx
      behaviors: update,delete,user,navigator,entity
    - name: PrcGrp
      client: sengee
      behaviors: update,delete,flow.create,flow.batchDelete
    - name: JobGrp
      client: sengee
      behaviors: update,delete,job.create,job.batchDelete
    - name: DataBase
      client: brackets
      behaviors: get,update,delete,test,schema.create,table.create,view.create
    - name: FileSystem
      client: brackets
      behaviors: get,update,delete,test,config.upload,dir.create,file.upload,file.delete
    - name: SteamService
      client: brackets
      behaviors: get,update,delete,test,channel
    - name: AppSystem
      alias: App
      client: brackets
      behaviors: get,update,delete
    - name: PromptGrp
      alias: PromptGrp
      client: sengee
      behaviors: prompt.import,create,update,delete

default:
  username: admin
