spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://datayoo.mysql:3306/brackets?characterEncoding=UTF8&useSSL=false
    username: root
    password: datayoo@123
    driverClassName: com.mysql.cj.jdbc.Driver
    initial-size: 5
    min-idle: 5
    max-idle: 100
    max-wait: 10000
    max-lifetime: 800000
    validation-queury: SELECT 1
    test-while-idle: true
    time-between-eviction-runs-millis: 27800
    test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  servlet:
    multipart:
      max-file-size: 700MB
      max-request-size: 700MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 38600
  servlet:
    context-path: /brackets


metadata:
  path: ./config/metadata

img:
  path: ./config/img


feign:
  hystrix:
    enabled: false
logging:
  config: classpath:logback-pro.xml

knife4j:
  enable: true

sengee:
  service:
    url: http://datayoo.sengee:38500/sengee

plugin:
  unDecompressionDir:
    path: ./config/plugin
jarGate:
  path: ./connectors/lib

authx:
  service:
    url: http://datayoo.authx:38700/authx
