#!/bin/bash

export DIR=`dirname $0`
export PRO=`basename $0`

DEBUG="-Xdebug -Xrunjdwp:transport=dt_socket,address=38505,server=y,suspend=n"

#JMX="-Dcom.sun.management.jmxremote.ssl=false \
#     -Dcom.sun.management.jmxremote.authenticate=false \
#     -Dcom.sun.management.jmxremote.port=30000"

if [ -f $NODE_HOME/java.policy ]; then
    JSTATD="jstatd -p 10000 -J-Djava.security.policy=$NODE_HOME/java.policy \
        -J-Djava.rmi.server.logCalls=true"
fi

export JAVA_OPTS="$DEBUG $JMX ${JAVA_OPTS}"

export JAVA_OPTS="-Xms1G -Xmx1G ${JAVA_OPTS}"

$DIR/node.sh $PRO $1  $2 
