#!/bin/sh

export DIR=`dirname $0`
export PRO=`basename $0`

export JAVA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=38801,server=y,suspend=n ${JAVA_OPTS}"
export JAVA_OPTS="${JAVA_OPTS} -Xms1G -Xmx1G"

$DIR/springboot.sh  $PRO org.datayoo.footstone.auth.gateway.GatewayApplication  $1 $2 

