#!/bin/sh

ALL="xxx yyy"

function getdir {
  if [ -h "$1" ];then
    dir=`readlink $1`
    dir=`dirname $dir`
    echo $dir
  else
    echo `dirname $1`
  fi
}

DIR=`getdir $0`

export BASE_DIR=$(cd $DIR/../>/dev/null;pwd)

. $DIR/functions || exit 0 

. $DIR/config || exit 0

operate="start|stop|restart|status|log"

HELP_STR=`echo $ALL | sed -e 's#\s#|#g'`

function help {
  echo "usage: $0  $HELP_STR $operate [stderr|stdout]"
}

if [ "$#" -lt "2" ]; then
  help;
  exit
fi

EXEC=${DIR}/$1

check_file_exec $EXEC 

case $2 in
  restart | start | stop | log | status )
  $EXEC $2 $3
  ;;
  *)
  help;
esac
