CREATE DATABASE IF NOT EXISTS  `authx` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';
CREATE DATABASE IF NOT EXISTS  `brackets` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci'; 
CREATE DATABASE IF NOT EXISTS  `sengee` CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci';
