#yc.cli.servers=172.31.179.129:8822
yc.cli.servers=datayoo.sengee:8822
yc.calling.expiration=20000
yc.cli.failure.retries=0
#yc.idle.interval=2000000

morten.node.id=mcpNode01
morten.node.leaf.configfile=./conf/mcp-flow.xml
morten.node.propsware.path=./propsware
morten.node.leaf.storagepath=./data
morten.node.leaf.configmode=LocalPriority
#morten.node.tags=nodeTypes:oyez,gosooz;clusters:spark1,spark2
morten.node.tags=nodeTypes:mcp
morten.node.comm.type=Netty
morten.node.leaf.workmode=Online

morten.node.leaf.shellserverport=39602

#oyez.node.port=32023
#oyez.node.log.conf=./conf/log.property
#oyez.node.nativeLibs=opencv_java460

#java.library.path=./ld
