yeeProps:
  yc.cli.servers: datayoo.sengee:8822
  yc.calling.expiration: 20000
  yc.cli.failure.retries: 0
  morten.node.id: 00000004
  yc.srv.work.threads: 32
envProperties:
  a: 1
  b: 2

#
##jarGateConfiguration:
##  jarGateName: HdfsJarGate #LocalJarGate
##  remoteLibPath: /tmp/hx/lib
##  localLibPath: ./data/operators/lib
##  gateProps:
##    settingsServiceId: jarGate
##
##fsConfiguration:
##  parameterFile: 'classpath:jargate/jarGate.xml'
##  baseDir: /
##  brokerName: jarGate
##  brokerType: hdfs
##  confFiles:
##    - 'classpath:jargate/core-site.xml'
##
parentFirstPatterns:
  - org.datayoo
parentFirstExcludePatterns:
  - org.datayoo.dencho.op
